apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
  namespace: santiago-parraga-dev
  labels:
    app: mi-app
    areanegocio: tecnologia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
        - name: contenedor-principal
          image: image-registry.openshift-image-registry.svc:5000/santiago-parraga-dev/ejercicio-codigo-s2i:latest  # <-- Reemplaza con la imagen que quieras usar
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap
            - secretRef:
                name: mi-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
  namespace: santiago-parraga-dev  # Asegúrate de que coincida con tu Deployment
spec:
  selector:
    app: mi-app  # Debe coincidir con las labels del Deployment
  ports:
    - protocol: TCP
      port: 4000        # Puerto del Service
      targetPort: 3000  # Puerto del contenedor
  type: ClusterIP     # Cambia a NodePort o LoadBalancer si quieres acceso externo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap
  namespace: santiago-parraga-dev
data:
  DATABASE: "192.168.1.1"
---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret
  namespace: santiago-parraga-dev
type: Opaque
data:
  PASSWORD: aG9sYQ==

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mi-hpa
  namespace: santiago-parraga-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: mi-deployment
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100
