apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ejercicio-codigo-s2i
  namespace: santiago-parraga-dev
  label:
    app: ejercicio-codigo-s2i
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ejercicio-codigo-s2i
  namespace: santiago-parraga-dev
  label:
    app: ejercicio-codigo-s2i
spec:
  source:
    type: Git
    git:
      uri: https://github.com/santiagoparragam/openshiftCourse.git
      ref: master
    contextDir: ''
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to: 
      kind: ImageStreamTag
      name: "ejercicio-codigo-s2i:latest"
