apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openshift-course-git
  label:
    app: openshift-course-git
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: openshift-course-git
  label:
    app: openshift-course-git
spec:
  source:
    type: Git
    git:
      uri: https://github.com/santiagoparragam/openshiftCourse.git
      ref: master
    contextDir: ''
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "python:3.12-ubi9"
  output:
    to: 
      kind: ImageStreamTag
      name: "openshift-course-git:latest"
