apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ejercicio-codigo-s2i
  label:
    app: ejercicio-codigo-s2i
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ejercicio-codigo-s2i
  label:
    app: ejercicio-codigo-s2i
spec:
  source:
    type: Git
    git:
      uri: https://github.com/santiagoparragam/openshiftCourse.git
      ref: main
    contextDir: ''
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: "python:3.12-ubi9"
  output:
    to: 
      kind: ImageStreamTag
      name: "ejercicio-codigo-s2i:latest"
